name: Prevent Direct Pushes to Main
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if commit is not from pull request
        run: |
          if [[ ! "${{ github.event.head_commit.message }}" =~ ^Merge\ pull\ request ]]; then
            echo "Direct pushes to main are not allowed. Use a pull request."
            exit 1
          fi

